package io.beldex.bchat.tescases;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.remote.MobileCapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import java.awt.*;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import static java.awt.event.KeyEvent.*;

public class SecretGroupChatCase {
    static String registerButton = "io.beldex.bchat:id/registerButton";
    static String logoimageview = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.ImageView";
    static String messagesendimageview ="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.RelativeLayout[2]/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.ImageView";
    static String Moreoptions = "More options";
    static String Notificationssettings ="/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[7]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.TextView";
    static String InputBarEditText = "io.beldex.bchat:id/inputBarEditText";
    static String CreatePrivateChatButton = "io.beldex.bchat:id/createPrivateChatButton";
    static String ActionIndicatorImageView ="io.beldex.bchat:id/actionIndicatorImageView";
    static String BtnSaveGroupNameEdit ="io.beldex.bchat:id/btnSaveGroupNameEdit";
    static String Action_apply ="io.beldex.bchat:id/action_apply";
    static String LblGroupNameDisplay ="io.beldex.bchat:id/lblGroupNameDisplay";
    //Appium Session settings to Connect with Android emulator
    public static void main(String[] args) throws MalformedURLException, InterruptedException, AWTException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        File Directory = new File("location");
        File Apk = new File(Directory, "Bchat-1.1.1-armeabi-v7a.apk");
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        capabilities.setCapability(MobileCapabilityType.APP, Apk.getAbsolutePath());
        capabilities.setCapability("appWaitActivity", "*");
        capabilities.setCapability("noReset", "True");
        AppiumDriver<MobileElement> driver = new AppiumDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        //driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        Thread.sleep(10000);

        //Create Account Flow
        MobileElement CreateAccountButton = (MobileElement) driver.findElementById(registerButton);
        CreateAccountButton.click();
        Thread.sleep(10000);
        MobileElement DisplayNameTextBox = (MobileElement) driver.findElementById("io.beldex.bchat:id/displayNameEditText");
        DisplayNameTextBox.sendKeys("sat");
        Thread.sleep(3000);
        MobileElement ContinueButton = (MobileElement) driver.findElementById(registerButton);
        ContinueButton.click();
        Thread.sleep(15000);
        MobileElement Next = (MobileElement) driver.findElementById(registerButton);
        Next.click();
        Thread.sleep(20000);
        MobileElement EnterPassword = (MobileElement) driver.findElementById("io.beldex.bchat:id/textinput_placeholder");
        EnterPassword.click();
        Thread.sleep(3000);
        Robot robot = new Robot();
        robot.keyPress(VK_0);
        robot.keyRelease(VK_0);
        robot.keyPress(VK_0);
        robot.keyRelease(VK_0);
        robot.keyPress(VK_0);
        robot.keyRelease(VK_0);
        robot.keyPress(VK_0);
        robot.keyRelease(VK_0);
        Thread.sleep(3000);
        MobileElement ReEnterPassword = (MobileElement) driver.findElementById("io.beldex.bchat:id/reEnterPinEditTxt");
        ReEnterPassword.click();
        Thread.sleep(3000);
        Robot robot2 = new Robot();
        robot2.keyPress(VK_0);
        robot2.keyRelease(VK_0);
        robot2.keyPress(VK_0);
        robot2.keyRelease(VK_0);
        robot2.keyPress(VK_0);
        robot2.keyRelease(VK_0);
        robot2.keyPress(VK_0);
        robot2.keyRelease(VK_0);
        robot2.keyPress(VK_0);
        robot2.keyRelease(VK_0);
        Thread.sleep(3000);
        MobileElement buttonNewenter = (MobileElement) driver.findElementById("io.beldex.bchat:id/buttonNew_enter");
        buttonNewenter.click();
        Thread.sleep(5000);
        MobileElement recoveryPhraseCopyIcon = (MobileElement) driver.findElementById("io.beldex.bchat:id/recoveryPhraseCopyIcon");
        recoveryPhraseCopyIcon.click();
        Thread.sleep(2000);
        MobileElement Nextbutton = (MobileElement) driver.findElementById(registerButton);
        Nextbutton.click();
        Thread.sleep(4000);

        //one to one contact creation
        MobileElement Logo = (MobileElement) driver.findElementByXPath(logoimageview);
        Logo.click();
        Thread.sleep(2000);
        MobileElement NewChat = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.RelativeLayout[1]/android.widget.ImageView");
        NewChat.click();
        Thread.sleep(2000);
        MobileElement publicKeytext = (MobileElement) driver.findElementById("io.beldex.bchat:id/publicKeyEditText");
        publicKeytext.sendKeys("bd047e3d1e66a52144d3e9fc8daa7af24566baa17a7c4f7ea9c3a82959c7c56200");
        Thread.sleep(2000);
        MobileElement createPrivatebutton = (MobileElement) driver.findElementById(CreatePrivateChatButton);
        createPrivatebutton.click();
        Thread.sleep(2000);
        MobileElement inputBarEditText = (MobileElement) driver.findElementById(InputBarEditText);
        inputBarEditText.sendKeys("Hello");
        Thread.sleep(2000);
        MobileElement Sendimageview = (MobileElement) driver.findElementByXPath(messagesendimageview);
        Sendimageview.click();
        Thread.sleep(40000);
        driver.navigate().back();
        Thread.sleep(20000);

        //Another one to one contact creation
        MobileElement Logo2 = (MobileElement) driver.findElementByXPath(logoimageview);
        Logo2.click();
        Thread.sleep(2000);
        MobileElement NewChat2 = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.RelativeLayout[1]/android.widget.ImageView");
        NewChat2.click();
        Thread.sleep(2000);
        MobileElement publicKeytext2 = (MobileElement) driver.findElementById("io.beldex.bchat:id/publicKeyEditText");
        publicKeytext2.sendKeys("bdb1ba00ebdbddc24213585d6e1523071b1fed74e711132d10e2e80800cfc35928");
        Thread.sleep(2000);
        MobileElement createPrivatebutton2 = (MobileElement) driver.findElementById(CreatePrivateChatButton);
        createPrivatebutton2.click();
        Thread.sleep(2000);
        MobileElement inputBarEditText2 = (MobileElement) driver.findElementById(InputBarEditText);
        inputBarEditText2.sendKeys("Hello");
        Thread.sleep(2000);
        MobileElement Sendimageview2 = (MobileElement) driver.findElementByXPath(messagesendimageview);
        Sendimageview2.click();
        Thread.sleep(40000);
        driver.navigate().back();
        Thread.sleep(20000);

        //Create secret group
        MobileElement Logo3 = (MobileElement) driver.findElementByXPath(logoimageview);
        Logo3.click();
        Thread.sleep(2000);
        MobileElement secretgroupimageview = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.RelativeLayout[2]/android.widget.ImageView");
        secretgroupimageview.click();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        MobileElement nameEditText = (MobileElement) driver.findElementById("io.beldex.bchat:id/nameEditText");
        nameEditText.sendKeys("Team");
        Thread.sleep(2000);
        MobileElement actionIndicatorImageView = (MobileElement) driver.findElementById(ActionIndicatorImageView);
        actionIndicatorImageView.click();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        MobileElement createNewPrivateButton = (MobileElement) driver.findElementById("io.beldex.bchat:id/createNewPrivateButton");
        createNewPrivateButton.click();
        Thread.sleep(10000);
        MobileElement inputBarEditText3 = (MobileElement) driver.findElementById(InputBarEditText);
        inputBarEditText3.sendKeys("Hello");
        Thread.sleep(2000);
        MobileElement Sendimageview3 = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.RelativeLayout[2]/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.ImageView");
        Sendimageview3.click();
        Thread.sleep(15000);

        //Check All media chat screen options for secret group
        MobileElement Moreoption = (MobileElement) driver.findElementByAccessibilityId(Moreoptions);
        Moreoption.click();
        Thread.sleep(3000);
        MobileElement Allmedia = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.TextView");
        Allmedia.click();
        Thread.sleep(3000);
        MobileElement Documents = (MobileElement) driver.findElementByXPath("//android.widget.LinearLayout[@content-desc=\"Documents\"]/android.widget.TextView");
        Documents.click();
        Thread.sleep(3000);
        MobileElement Media = (MobileElement) driver.findElementByXPath("//android.widget.LinearLayout[@content-desc=\"Media\"]/android.widget.TextView");
        Media.click();
        Thread.sleep(3000);
        MobileElement Navigateupbutton = (MobileElement) driver.findElementByAccessibilityId("Navigate up");
        Navigateupbutton.click();
        Thread.sleep(5000);

        //Check Search chat screen options for secret group
        MobileElement Moreoption2 = (MobileElement) driver.findElementByAccessibilityId(Moreoptions);
        Moreoption2.click();
        Thread.sleep(5000);
        MobileElement Search = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.TextView");
        Search.click();
        Thread.sleep(3000);
        MobileElement searchtext = (MobileElement) driver.findElementById("io.beldex.bchat:id/search_src_text");
        searchtext.sendKeys("He");
        Thread.sleep(5000);
        MobileElement Collapse = (MobileElement) driver.findElementByAccessibilityId("Collapse");
        Collapse.click();
        Thread.sleep(3000);

        //Check add to home screen chat screen options for secret group
        MobileElement Moreoption3 = (MobileElement) driver.findElementByAccessibilityId(Moreoptions);
        Moreoption3.click();
        Thread.sleep(3000);
        MobileElement Addtohomescreen = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[3]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.TextView");
        Addtohomescreen.click();
        Thread.sleep(3000);
        MobileElement Addautomaticallybutton = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.Button[2]");
        Addautomaticallybutton.click();
        Thread.sleep(3000);

        //Check mute and unmute chat screen options for secret group
        MobileElement Moreoption4 = (MobileElement) driver.findElementByAccessibilityId(Moreoptions);
        Moreoption4.click();
        Thread.sleep(3000);
        MobileElement Mutenotifications = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[6]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.TextView");
        Mutenotifications.click();
        Thread.sleep(3000);
        MobileElement Mutefor1hour = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.appcompat.widget.LinearLayoutCompat/android.widget.FrameLayout/android.widget.ListView/android.widget.TextView[1]");
        Mutefor1hour.click();
        Thread.sleep(3000);
        MobileElement Moreoption7 = (MobileElement) driver.findElementByAccessibilityId(Moreoptions);
        Moreoption7.click();
        Thread.sleep(3000);
        MobileElement Unmute = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[6]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.TextView");
        Unmute.click();
        Thread.sleep(3000);

        //Check notifications settings chat screen options for secret group
        MobileElement Moreoption5 = (MobileElement) driver.findElementByAccessibilityId(Moreoptions);
        Moreoption5.click();
        Thread.sleep(3000);
        MobileElement Notificationsettingstextview = (MobileElement) driver.findElementByXPath(Notificationssettings);
        Notificationsettingstextview.click();
        Thread.sleep(3000);
        MobileElement MentionsCheckedTextView = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.appcompat.widget.LinearLayoutCompat/android.widget.FrameLayout/android.widget.ListView/android.widget.CheckedTextView[2]");
        MentionsCheckedTextView.click();
        Thread.sleep(3000);
        MobileElement Moreoption6 = (MobileElement) driver.findElementByAccessibilityId(Moreoptions);
        Moreoption6.click();
        Thread.sleep(3000);
        MobileElement Notificationsettingstextview2 = (MobileElement) driver.findElementByXPath(Notificationssettings);
        Notificationsettingstextview2.click();
        Thread.sleep(3000);
        MobileElement AllCheckedTextView = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.appcompat.widget.LinearLayoutCompat/android.widget.FrameLayout/android.widget.ListView/android.widget.CheckedTextView[1]");
        AllCheckedTextView.click();
        Thread.sleep(3000);

        //Check Edit group option on secret group chat screen
        MobileElement Moreoption8 = (MobileElement) driver.findElementByAccessibilityId(Moreoptions);
        Moreoption8.click();
        Thread.sleep(3000);
        MobileElement Editgrouptextview = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[4]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.TextView");
        Editgrouptextview.click();
        Thread.sleep(3000);

        //Check for giving lengthy group name on edit group page
        MobileElement lblGroupNameDisplay = (MobileElement) driver.findElementById(LblGroupNameDisplay);
        lblGroupNameDisplay.click();
        Thread.sleep(3000);
        Robot robot3 = new Robot();
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(1000);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(1000);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_T);
        Thread.sleep(1000);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(1000);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(1000);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(1000);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_T);
        Thread.sleep(1000);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(1000);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(1000);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(1000);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(1000);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(1000);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(1000);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(1000);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(1000);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        robot3.keyPress(VK_E);
        robot3.keyRelease(VK_E);
        robot3.keyPress(VK_S);
        robot3.keyRelease(VK_S);
        robot3.keyPress(VK_T);
        robot3.keyRelease(VK_T);
        Thread.sleep(10000);
        MobileElement btnSaveGroupNameEdit = (MobileElement) driver.findElementById(BtnSaveGroupNameEdit);
        btnSaveGroupNameEdit.click();
        Thread.sleep(3000);
        MobileElement action_apply = (MobileElement) driver.findElementById(Action_apply);
        action_apply.click();
        Thread.sleep(3000);
        MobileElement Moreoption9 = (MobileElement) driver.findElementByAccessibilityId(Moreoptions);
        Moreoption9.click();
        Thread.sleep(3000);
        MobileElement Editgrouptextview2 = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[4]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.TextView");
        Editgrouptextview2.click();
        Thread.sleep(3000);

        //Check for giving valid group name on edit group page
        MobileElement lblGroupNameDisplay2 = (MobileElement) driver.findElementById(LblGroupNameDisplay);
        lblGroupNameDisplay2.click();
        Thread.sleep(3000);
        Robot robot4 = new Robot();
        robot4.keyPress(VK_T);
        robot4.keyRelease(VK_T);
        robot4.keyPress(VK_E);
        robot4.keyRelease(VK_E);
        robot4.keyPress(VK_S);
        robot4.keyRelease(VK_S);
        robot4.keyPress(VK_T);
        robot4.keyRelease(VK_T);
        Thread.sleep(3000);
        MobileElement btnSaveGroupNameEdit2 = (MobileElement) driver.findElementById(BtnSaveGroupNameEdit);
        btnSaveGroupNameEdit2.click();
        Thread.sleep(3000);
        MobileElement action_apply2 = (MobileElement) driver.findElementById(Action_apply);
        action_apply2.click();
        Thread.sleep(3000);

        //Check add members option on edit group page
        MobileElement Moreoption10 = (MobileElement) driver.findElementByAccessibilityId(Moreoptions);
        Moreoption10.click();
        Thread.sleep(3000);
        MobileElement Editgrouptextview3 = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[4]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.TextView");
        Editgrouptextview3.click();
        Thread.sleep(3000);
        MobileElement addMembersClosedGroupButton = (MobileElement) driver.findElementById("io.beldex.bchat:id/addMembersClosedGroupButton");
        addMembersClosedGroupButton.click();
        Thread.sleep(3000);
        MobileElement actionIndicatorImageView2 = (MobileElement) driver.findElementById(ActionIndicatorImageView);
        actionIndicatorImageView2.click();
        Thread.sleep(3000);
        MobileElement donebutton = (MobileElement) driver.findElementByAccessibilityId("Done");
        donebutton.click();
        Thread.sleep(3000);

        //Check remove members from group option on edit group page
        MobileElement nameTextView = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.RelativeLayout/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.TextView");
        nameTextView.click();
        Thread.sleep(3000);
        MobileElement removeFromGroup = (MobileElement) driver.findElementById("io.beldex.bchat:id/removeFromGroup");
        removeFromGroup.click();
        Thread.sleep(3000);
        MobileElement action_apply3 = (MobileElement) driver.findElementById(Action_apply);
        action_apply3.click();
        Thread.sleep(3000);

        //Check leave group option on secret group chat screen
        MobileElement Moreoption11 = (MobileElement) driver.findElementByAccessibilityId(Moreoptions);
        Moreoption11.click();
        Thread.sleep(3000);
        MobileElement LeavegroupTextView = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[5]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.TextView");
        LeavegroupTextView.click();
        Thread.sleep(3000);
        MobileElement leavebutton = (MobileElement) driver.findElementById("android:id/button1");
        leavebutton.click();
    }
}
